log:
  level: "info"
  format: "text"

listen_addr: "0.0.0.0:5678"

processors:
  # write logs to a one file per node
  filelogger: true
  # forward the logs ("https://log.tailscale.io" to forward to tailscale)
  forward: ""
  # expose the metrics contained in the logs in the prometheus format
  metrics: false
  # log the node's host info to the console
  hostinfo: false

filelogger:
  dir: "./logs"

ssh_recorder:
  listen_addr: "0.0.0.0:80" # the port usually is :80
  dir: "./recordings"
