log:
  level: "info"
  format: "text"

loghead:
  processors:
    # write logs to a one file per node
    filelogger:
      enabled: true
      dir: "./logs"
    # forward the logs to another logtail instance
    forward:
      enabled: false
      addr: "https://log.tailscale.io"
    # expose the metrics contained in the logs in the prometheus format
    metrics: false
    # log the node's host info to the console
    hostinfo: false
  listener:
    type: "plain" # "plain" or "tsnet"
    addr: "0.0.0.0"
    port: "5678"

ssh_recorder:
  dir: "./recordings"
  listener:
    type: "tsnet" # "plain" or "tsnet"
    addr: "0.0.0.0"
    port: "80"
